# Generated by Django 4.2 on 2023-04-16 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Juntuan',
            fields=[
                ('juntuan_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('alliance', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Renwu',
            fields=[
                ('game_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('point', models.BigIntegerField(blank=True, null=True)),
                ('juntuan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.juntuan')),
                ('user_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jiandui',
            fields=[
                ('jiandui_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timeCreate', models.DateTimeField(auto_now=True)),
                ('spr', models.BooleanField()),
                ('member', models.JSONField()),
                ('fc_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='website.renwu')),
            ],
        ),
    ]
