# Generated by Django 4.2 on 2023-04-17 00:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0003_alter_renwu_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='renwu',
            name='user_name',
        ),
        migrations.AddField(
            model_name='renwu',
            name='user_name',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
