# Generated by Django 4.2 on 2023-04-17 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_remove_renwu_user_name_renwu_user_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='juntuan',
            name='alliance',
        ),
    ]
