# Generated by Django 4.2 on 2023-04-17 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('website', '0007_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fc',
            fields=[
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fc', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
