# Generated by Django 4.2 on 2023-04-25 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0008_fc_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corporation',
            fields=[
                ('category', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='fc',
            name='fc',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fc',
            name='user_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
