# Generated by Django 4.2 on 2023-04-26 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_corporation_alter_fc_fc_alter_fc_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Corporation',
        ),
    ]
