# Generated by Django 4.2 on 2023-04-27 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_delete_corporation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jiandui',
            name='fc_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='website.renwu'),
        ),
    ]
